// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReviewsSite.Models;

namespace ReviewsSite.Migrations
{
    [DbContext(typeof(MoviesContext))]
    [Migration("20181019191218_ReviewData")]
    partial class ReviewData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ReviewsSite.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content");

                    b.Property<DateTime>("Date");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("ReviewCategory");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Reviews");

                    b.HasData(
                        new { Id = 1, Content = "It was an ok movie, I guess.", Date = new DateTime(2010, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), ImageUrl = "/images/spiderman.jpg", ReviewCategory = "Action", Title = "Spiderman" },
                        new { Id = 2, Content = "It was great-ish", Date = new DateTime(2009, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), ImageUrl = "/images/batman.jpg", ReviewCategory = "Action", Title = "Batman" },
                        new { Id = 3, Content = "It was a awesome!", Date = new DateTime(2008, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), ImageUrl = "/images/xmen.jpg", ReviewCategory = "Action", Title = "X-Men" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
